package com.ls.FreightTransport.entity;

public class CollectFees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_fees.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_fees.c_date
     *
     * @mbg.generated
     */
    private String cDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_fees.c_mileage
     *
     * @mbg.generated
     */
    private String cMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_fees.c_starting
     *
     * @mbg.generated
     */
    private String cStarting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_fees.c_remarks
     *
     * @mbg.generated
     */
    private String cRemarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_fees.c_type
     *
     * @mbg.generated
     */
    private String cType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_fees.c_id
     *
     * @return the value of collect_fees.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_fees.c_id
     *
     * @param cId the value for collect_fees.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_fees.c_date
     *
     * @return the value of collect_fees.c_date
     *
     * @mbg.generated
     */
    public String getcDate() {
        return cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_fees.c_date
     *
     * @param cDate the value for collect_fees.c_date
     *
     * @mbg.generated
     */
    public void setcDate(String cDate) {
        this.cDate = cDate == null ? null : cDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_fees.c_mileage
     *
     * @return the value of collect_fees.c_mileage
     *
     * @mbg.generated
     */
    public String getcMileage() {
        return cMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_fees.c_mileage
     *
     * @param cMileage the value for collect_fees.c_mileage
     *
     * @mbg.generated
     */
    public void setcMileage(String cMileage) {
        this.cMileage = cMileage == null ? null : cMileage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_fees.c_starting
     *
     * @return the value of collect_fees.c_starting
     *
     * @mbg.generated
     */
    public String getcStarting() {
        return cStarting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_fees.c_starting
     *
     * @param cStarting the value for collect_fees.c_starting
     *
     * @mbg.generated
     */
    public void setcStarting(String cStarting) {
        this.cStarting = cStarting == null ? null : cStarting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_fees.c_remarks
     *
     * @return the value of collect_fees.c_remarks
     *
     * @mbg.generated
     */
    public String getcRemarks() {
        return cRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_fees.c_remarks
     *
     * @param cRemarks the value for collect_fees.c_remarks
     *
     * @mbg.generated
     */
    public void setcRemarks(String cRemarks) {
        this.cRemarks = cRemarks == null ? null : cRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_fees.c_type
     *
     * @return the value of collect_fees.c_type
     *
     * @mbg.generated
     */
    public String getcType() {
        return cType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_fees.c_type
     *
     * @param cType the value for collect_fees.c_type
     *
     * @mbg.generated
     */
    public void setcType(String cType) {
        this.cType = cType == null ? null : cType.trim();
    }
}