package com.ls.FreightTransport.entity;

public class EvaluationInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_info.e_id
     *
     * @mbg.generated
     */
    private Integer eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_info.o_id
     *
     * @mbg.generated
     */
    private String oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_info.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_info.d_name
     *
     * @mbg.generated
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_info.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_info.s_name
     *
     * @mbg.generated
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_info.e_fraction
     *
     * @mbg.generated
     */
    private String eFraction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluation_info.e_content
     *
     * @mbg.generated
     */
    private String eContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_info.e_id
     *
     * @return the value of evaluation_info.e_id
     *
     * @mbg.generated
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_info.e_id
     *
     * @param eId the value for evaluation_info.e_id
     *
     * @mbg.generated
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_info.o_id
     *
     * @return the value of evaluation_info.o_id
     *
     * @mbg.generated
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_info.o_id
     *
     * @param oId the value for evaluation_info.o_id
     *
     * @mbg.generated
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_info.d_id
     *
     * @return the value of evaluation_info.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_info.d_id
     *
     * @param dId the value for evaluation_info.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_info.d_name
     *
     * @return the value of evaluation_info.d_name
     *
     * @mbg.generated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_info.d_name
     *
     * @param dName the value for evaluation_info.d_name
     *
     * @mbg.generated
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_info.s_id
     *
     * @return the value of evaluation_info.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_info.s_id
     *
     * @param sId the value for evaluation_info.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_info.s_name
     *
     * @return the value of evaluation_info.s_name
     *
     * @mbg.generated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_info.s_name
     *
     * @param sName the value for evaluation_info.s_name
     *
     * @mbg.generated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_info.e_fraction
     *
     * @return the value of evaluation_info.e_fraction
     *
     * @mbg.generated
     */
    public String geteFraction() {
        return eFraction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_info.e_fraction
     *
     * @param eFraction the value for evaluation_info.e_fraction
     *
     * @mbg.generated
     */
    public void seteFraction(String eFraction) {
        this.eFraction = eFraction == null ? null : eFraction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluation_info.e_content
     *
     * @return the value of evaluation_info.e_content
     *
     * @mbg.generated
     */
    public String geteContent() {
        return eContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluation_info.e_content
     *
     * @param eContent the value for evaluation_info.e_content
     *
     * @mbg.generated
     */
    public void seteContent(String eContent) {
        this.eContent = eContent == null ? null : eContent.trim();
    }
}