package com.ls.FreightTransport.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FinancialInfoSheet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_info_sheet.f_id
     *
     * @mbg.generated
     */
    private Integer fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_info_sheet.f_befor_money
     *
     * @mbg.generated
     */
    private BigDecimal fBeforMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_info_sheet.f_after_money
     *
     * @mbg.generated
     */
    private BigDecimal fAfterMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_info_sheet.f_money
     *
     * @mbg.generated
     */
    private BigDecimal fMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_info_sheet.f_type
     *
     * @mbg.generated
     */
    private String fType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_info_sheet.f_name_type
     *
     * @mbg.generated
     */
    private String fNameType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_info_sheet.f_ids
     *
     * @mbg.generated
     */
    private Integer fIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_info_sheet.f_name
     *
     * @mbg.generated
     */
    private String fName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_info_sheet.f_date
     *
     * @mbg.generated
     */
    private Date fDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_info_sheet.f_remarks
     *
     * @mbg.generated
     */
    private String fRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_info_sheet.f_id
     *
     * @return the value of financial_info_sheet.f_id
     *
     * @mbg.generated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_info_sheet.f_id
     *
     * @param fId the value for financial_info_sheet.f_id
     *
     * @mbg.generated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_info_sheet.f_befor_money
     *
     * @return the value of financial_info_sheet.f_befor_money
     *
     * @mbg.generated
     */
    public BigDecimal getfBeforMoney() {
        return fBeforMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_info_sheet.f_befor_money
     *
     * @param fBeforMoney the value for financial_info_sheet.f_befor_money
     *
     * @mbg.generated
     */
    public void setfBeforMoney(BigDecimal fBeforMoney) {
        this.fBeforMoney = fBeforMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_info_sheet.f_after_money
     *
     * @return the value of financial_info_sheet.f_after_money
     *
     * @mbg.generated
     */
    public BigDecimal getfAfterMoney() {
        return fAfterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_info_sheet.f_after_money
     *
     * @param fAfterMoney the value for financial_info_sheet.f_after_money
     *
     * @mbg.generated
     */
    public void setfAfterMoney(BigDecimal fAfterMoney) {
        this.fAfterMoney = fAfterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_info_sheet.f_money
     *
     * @return the value of financial_info_sheet.f_money
     *
     * @mbg.generated
     */
    public BigDecimal getfMoney() {
        return fMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_info_sheet.f_money
     *
     * @param fMoney the value for financial_info_sheet.f_money
     *
     * @mbg.generated
     */
    public void setfMoney(BigDecimal fMoney) {
        this.fMoney = fMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_info_sheet.f_type
     *
     * @return the value of financial_info_sheet.f_type
     *
     * @mbg.generated
     */
    public String getfType() {
        return fType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_info_sheet.f_type
     *
     * @param fType the value for financial_info_sheet.f_type
     *
     * @mbg.generated
     */
    public void setfType(String fType) {
        this.fType = fType == null ? null : fType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_info_sheet.f_name_type
     *
     * @return the value of financial_info_sheet.f_name_type
     *
     * @mbg.generated
     */
    public String getfNameType() {
        return fNameType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_info_sheet.f_name_type
     *
     * @param fNameType the value for financial_info_sheet.f_name_type
     *
     * @mbg.generated
     */
    public void setfNameType(String fNameType) {
        this.fNameType = fNameType == null ? null : fNameType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_info_sheet.f_ids
     *
     * @return the value of financial_info_sheet.f_ids
     *
     * @mbg.generated
     */
    public Integer getfIds() {
        return fIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_info_sheet.f_ids
     *
     * @param fIds the value for financial_info_sheet.f_ids
     *
     * @mbg.generated
     */
    public void setfIds(Integer fIds) {
        this.fIds = fIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_info_sheet.f_name
     *
     * @return the value of financial_info_sheet.f_name
     *
     * @mbg.generated
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_info_sheet.f_name
     *
     * @param fName the value for financial_info_sheet.f_name
     *
     * @mbg.generated
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_info_sheet.f_date
     *
     * @return the value of financial_info_sheet.f_date
     *
     * @mbg.generated
     */
    public Date getfDate() {
        return fDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_info_sheet.f_date
     *
     * @param fDate the value for financial_info_sheet.f_date
     *
     * @mbg.generated
     */
    public void setfDate(Date fDate) {
        this.fDate = fDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_info_sheet.f_remarks
     *
     * @return the value of financial_info_sheet.f_remarks
     *
     * @mbg.generated
     */
    public String getfRemarks() {
        return fRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_info_sheet.f_remarks
     *
     * @param fRemarks the value for financial_info_sheet.f_remarks
     *
     * @mbg.generated
     */
    public void setfRemarks(String fRemarks) {
        this.fRemarks = fRemarks == null ? null : fRemarks.trim();
    }
}