package com.ls.FreightTransport.entity;

import java.math.BigDecimal;

public class LocateInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locate_info.l_id
     *
     * @mbg.generated
     */
    private Integer lId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locate_info.l_add_name
     *
     * @mbg.generated
     */
    private String lAddName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locate_info.l_end_name
     *
     * @mbg.generated
     */
    private String lEndName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locate_info.l_add_ip
     *
     * @mbg.generated
     */
    private String lAddIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locate_info.l_end_ip
     *
     * @mbg.generated
     */
    private String lEndIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locate_info.l_price
     *
     * @mbg.generated
     */
    private BigDecimal lPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locate_info.l_type
     *
     * @mbg.generated
     */
    private Integer lType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locate_info.l_pei_yong
     *
     * @mbg.generated
     */
    private String lPeiYong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locate_info.l_pei_yongs
     *
     * @mbg.generated
     */
    private String lPeiYongs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locate_info.l_id
     *
     * @return the value of locate_info.l_id
     *
     * @mbg.generated
     */
    public Integer getlId() {
        return lId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locate_info.l_id
     *
     * @param lId the value for locate_info.l_id
     *
     * @mbg.generated
     */
    public void setlId(Integer lId) {
        this.lId = lId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locate_info.l_add_name
     *
     * @return the value of locate_info.l_add_name
     *
     * @mbg.generated
     */
    public String getlAddName() {
        return lAddName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locate_info.l_add_name
     *
     * @param lAddName the value for locate_info.l_add_name
     *
     * @mbg.generated
     */
    public void setlAddName(String lAddName) {
        this.lAddName = lAddName == null ? null : lAddName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locate_info.l_end_name
     *
     * @return the value of locate_info.l_end_name
     *
     * @mbg.generated
     */
    public String getlEndName() {
        return lEndName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locate_info.l_end_name
     *
     * @param lEndName the value for locate_info.l_end_name
     *
     * @mbg.generated
     */
    public void setlEndName(String lEndName) {
        this.lEndName = lEndName == null ? null : lEndName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locate_info.l_add_ip
     *
     * @return the value of locate_info.l_add_ip
     *
     * @mbg.generated
     */
    public String getlAddIp() {
        return lAddIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locate_info.l_add_ip
     *
     * @param lAddIp the value for locate_info.l_add_ip
     *
     * @mbg.generated
     */
    public void setlAddIp(String lAddIp) {
        this.lAddIp = lAddIp == null ? null : lAddIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locate_info.l_end_ip
     *
     * @return the value of locate_info.l_end_ip
     *
     * @mbg.generated
     */
    public String getlEndIp() {
        return lEndIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locate_info.l_end_ip
     *
     * @param lEndIp the value for locate_info.l_end_ip
     *
     * @mbg.generated
     */
    public void setlEndIp(String lEndIp) {
        this.lEndIp = lEndIp == null ? null : lEndIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locate_info.l_price
     *
     * @return the value of locate_info.l_price
     *
     * @mbg.generated
     */
    public BigDecimal getlPrice() {
        return lPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locate_info.l_price
     *
     * @param lPrice the value for locate_info.l_price
     *
     * @mbg.generated
     */
    public void setlPrice(BigDecimal lPrice) {
        this.lPrice = lPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locate_info.l_type
     *
     * @return the value of locate_info.l_type
     *
     * @mbg.generated
     */
    public Integer getlType() {
        return lType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locate_info.l_type
     *
     * @param lType the value for locate_info.l_type
     *
     * @mbg.generated
     */
    public void setlType(Integer lType) {
        this.lType = lType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locate_info.l_pei_yong
     *
     * @return the value of locate_info.l_pei_yong
     *
     * @mbg.generated
     */
    public String getlPeiYong() {
        return lPeiYong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locate_info.l_pei_yong
     *
     * @param lPeiYong the value for locate_info.l_pei_yong
     *
     * @mbg.generated
     */
    public void setlPeiYong(String lPeiYong) {
        this.lPeiYong = lPeiYong == null ? null : lPeiYong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locate_info.l_pei_yongs
     *
     * @return the value of locate_info.l_pei_yongs
     *
     * @mbg.generated
     */
    public String getlPeiYongs() {
        return lPeiYongs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locate_info.l_pei_yongs
     *
     * @param lPeiYongs the value for locate_info.l_pei_yongs
     *
     * @mbg.generated
     */
    public void setlPeiYongs(String lPeiYongs) {
        this.lPeiYongs = lPeiYongs == null ? null : lPeiYongs.trim();
    }
}