package com.ls.FreightTransport.entity;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_account
     *
     * @mbg.generated
     */
    private String mAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_password
     *
     * @mbg.generated
     */
    private String mPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_phone
     *
     * @mbg.generated
     */
    private String mPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_rank
     *
     * @mbg.generated
     */
    private String mRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_remarks
     *
     * @mbg.generated
     */
    private String mRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_id
     *
     * @return the value of manager.m_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_id
     *
     * @param mId the value for manager.m_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_account
     *
     * @return the value of manager.m_account
     *
     * @mbg.generated
     */
    public String getmAccount() {
        return mAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_account
     *
     * @param mAccount the value for manager.m_account
     *
     * @mbg.generated
     */
    public void setmAccount(String mAccount) {
        this.mAccount = mAccount == null ? null : mAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_password
     *
     * @return the value of manager.m_password
     *
     * @mbg.generated
     */
    public String getmPassword() {
        return mPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_password
     *
     * @param mPassword the value for manager.m_password
     *
     * @mbg.generated
     */
    public void setmPassword(String mPassword) {
        this.mPassword = mPassword == null ? null : mPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_phone
     *
     * @return the value of manager.m_phone
     *
     * @mbg.generated
     */
    public String getmPhone() {
        return mPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_phone
     *
     * @param mPhone the value for manager.m_phone
     *
     * @mbg.generated
     */
    public void setmPhone(String mPhone) {
        this.mPhone = mPhone == null ? null : mPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_rank
     *
     * @return the value of manager.m_rank
     *
     * @mbg.generated
     */
    public String getmRank() {
        return mRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_rank
     *
     * @param mRank the value for manager.m_rank
     *
     * @mbg.generated
     */
    public void setmRank(String mRank) {
        this.mRank = mRank == null ? null : mRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_remarks
     *
     * @return the value of manager.m_remarks
     *
     * @mbg.generated
     */
    public String getmRemarks() {
        return mRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_remarks
     *
     * @param mRemarks the value for manager.m_remarks
     *
     * @mbg.generated
     */
    public void setmRemarks(String mRemarks) {
        this.mRemarks = mRemarks == null ? null : mRemarks.trim();
    }
}