package com.ls.FreightTransport.entity;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.n_infro_id
     *
     * @mbg.generated
     */
    private Integer nInfroId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.n_content
     *
     * @mbg.generated
     */
    private String nContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.n_direction
     *
     * @mbg.generated
     */
    private String nDirection;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.n_infro_id
     *
     * @return the value of notice.n_infro_id
     *
     * @mbg.generated
     */
    public Integer getnInfroId() {
        return nInfroId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.n_infro_id
     *
     * @param nInfroId the value for notice.n_infro_id
     *
     * @mbg.generated
     */
    public void setnInfroId(Integer nInfroId) {
        this.nInfroId = nInfroId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.n_content
     *
     * @return the value of notice.n_content
     *
     * @mbg.generated
     */
    public String getnContent() {
        return nContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.n_content
     *
     * @param nContent the value for notice.n_content
     *
     * @mbg.generated
     */
    public void setnContent(String nContent) {
        this.nContent = nContent == null ? null : nContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.n_direction
     *
     * @return the value of notice.n_direction
     *
     * @mbg.generated
     */
    public String getnDirection() {
        return nDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.n_direction
     *
     * @param nDirection the value for notice.n_direction
     *
     * @mbg.generated
     */
    public void setnDirection(String nDirection) {
        this.nDirection = nDirection == null ? null : nDirection.trim();
    }
}