package com.ls.FreightTransport.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.o_id
     *
     * @mbg.generated
     */
    private String oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.o_type
     *
     * @mbg.generated
     */
    private Integer oType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.o_contacts
     *
     * @mbg.generated
     */
    private String oContacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.o_start_date
     *
     * @mbg.generated
     */
    private Date oStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.o_end_date
     *
     * @mbg.generated
     */
    private Date oEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.o_price
     *
     * @mbg.generated
     */
    private BigDecimal oPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.o_shipping_address
     *
     * @mbg.generated
     */
    private String oShippingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.o_receiving_address
     *
     * @mbg.generated
     */
    private String oReceivingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.o_state
     *
     * @mbg.generated
     */
    private String oState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.o_remarks
     *
     * @mbg.generated
     */
    private String oRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.o_id
     *
     * @return the value of order_info.o_id
     *
     * @mbg.generated
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.o_id
     *
     * @param oId the value for order_info.o_id
     *
     * @mbg.generated
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.o_type
     *
     * @return the value of order_info.o_type
     *
     * @mbg.generated
     */
    public Integer getoType() {
        return oType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.o_type
     *
     * @param oType the value for order_info.o_type
     *
     * @mbg.generated
     */
    public void setoType(Integer oType) {
        this.oType = oType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.o_contacts
     *
     * @return the value of order_info.o_contacts
     *
     * @mbg.generated
     */
    public String getoContacts() {
        return oContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.o_contacts
     *
     * @param oContacts the value for order_info.o_contacts
     *
     * @mbg.generated
     */
    public void setoContacts(String oContacts) {
        this.oContacts = oContacts == null ? null : oContacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.o_start_date
     *
     * @return the value of order_info.o_start_date
     *
     * @mbg.generated
     */
    public Date getoStartDate() {
        return oStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.o_start_date
     *
     * @param oStartDate the value for order_info.o_start_date
     *
     * @mbg.generated
     */
    public void setoStartDate(Date oStartDate) {
        this.oStartDate = oStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.o_end_date
     *
     * @return the value of order_info.o_end_date
     *
     * @mbg.generated
     */
    public Date getoEndDate() {
        return oEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.o_end_date
     *
     * @param oEndDate the value for order_info.o_end_date
     *
     * @mbg.generated
     */
    public void setoEndDate(Date oEndDate) {
        this.oEndDate = oEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.o_price
     *
     * @return the value of order_info.o_price
     *
     * @mbg.generated
     */
    public BigDecimal getoPrice() {
        return oPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.o_price
     *
     * @param oPrice the value for order_info.o_price
     *
     * @mbg.generated
     */
    public void setoPrice(BigDecimal oPrice) {
        this.oPrice = oPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.o_shipping_address
     *
     * @return the value of order_info.o_shipping_address
     *
     * @mbg.generated
     */
    public String getoShippingAddress() {
        return oShippingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.o_shipping_address
     *
     * @param oShippingAddress the value for order_info.o_shipping_address
     *
     * @mbg.generated
     */
    public void setoShippingAddress(String oShippingAddress) {
        this.oShippingAddress = oShippingAddress == null ? null : oShippingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.o_receiving_address
     *
     * @return the value of order_info.o_receiving_address
     *
     * @mbg.generated
     */
    public String getoReceivingAddress() {
        return oReceivingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.o_receiving_address
     *
     * @param oReceivingAddress the value for order_info.o_receiving_address
     *
     * @mbg.generated
     */
    public void setoReceivingAddress(String oReceivingAddress) {
        this.oReceivingAddress = oReceivingAddress == null ? null : oReceivingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.s_id
     *
     * @return the value of order_info.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.s_id
     *
     * @param sId the value for order_info.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.d_id
     *
     * @return the value of order_info.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.d_id
     *
     * @param dId the value for order_info.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.o_state
     *
     * @return the value of order_info.o_state
     *
     * @mbg.generated
     */
    public String getoState() {
        return oState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.o_state
     *
     * @param oState the value for order_info.o_state
     *
     * @mbg.generated
     */
    public void setoState(String oState) {
        this.oState = oState == null ? null : oState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.o_remarks
     *
     * @return the value of order_info.o_remarks
     *
     * @mbg.generated
     */
    public String getoRemarks() {
        return oRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.o_remarks
     *
     * @param oRemarks the value for order_info.o_remarks
     *
     * @mbg.generated
     */
    public void setoRemarks(String oRemarks) {
        this.oRemarks = oRemarks == null ? null : oRemarks.trim();
    }
}