package com.ls.FreightTransport.entity;

public class SCollect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_collect.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_collect.s_phone
     *
     * @mbg.generated
     */
    private String sPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_collect.s_NAME
     *
     * @mbg.generated
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_collect.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_collect.c_id
     *
     * @return the value of s_collect.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_collect.c_id
     *
     * @param cId the value for s_collect.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_collect.s_phone
     *
     * @return the value of s_collect.s_phone
     *
     * @mbg.generated
     */
    public String getsPhone() {
        return sPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_collect.s_phone
     *
     * @param sPhone the value for s_collect.s_phone
     *
     * @mbg.generated
     */
    public void setsPhone(String sPhone) {
        this.sPhone = sPhone == null ? null : sPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_collect.s_NAME
     *
     * @return the value of s_collect.s_NAME
     *
     * @mbg.generated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_collect.s_NAME
     *
     * @param sName the value for s_collect.s_NAME
     *
     * @mbg.generated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_collect.s_id
     *
     * @return the value of s_collect.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_collect.s_id
     *
     * @param sId the value for s_collect.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }
}