package com.ls.FreightTransport.entity;

import java.util.Date;

public class StaffInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_info.s_no
     *
     * @mbg.generated
     */
    private Integer sNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_info.s_name
     *
     * @mbg.generated
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_info.s_sex
     *
     * @mbg.generated
     */
    private String sSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_info.s_birthhday
     *
     * @mbg.generated
     */
    private Date sBirthhday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_info.s_phone
     *
     * @mbg.generated
     */
    private String sPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_info.s_password
     *
     * @mbg.generated
     */
    private String sPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_info.s_firm_name
     *
     * @mbg.generated
     */
    private String sFirmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_info.s_remarks
     *
     * @mbg.generated
     */
    private String sRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_info.s_no
     *
     * @return the value of staff_info.s_no
     *
     * @mbg.generated
     */
    public Integer getsNo() {
        return sNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_info.s_no
     *
     * @param sNo the value for staff_info.s_no
     *
     * @mbg.generated
     */
    public void setsNo(Integer sNo) {
        this.sNo = sNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_info.s_name
     *
     * @return the value of staff_info.s_name
     *
     * @mbg.generated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_info.s_name
     *
     * @param sName the value for staff_info.s_name
     *
     * @mbg.generated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_info.s_sex
     *
     * @return the value of staff_info.s_sex
     *
     * @mbg.generated
     */
    public String getsSex() {
        return sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_info.s_sex
     *
     * @param sSex the value for staff_info.s_sex
     *
     * @mbg.generated
     */
    public void setsSex(String sSex) {
        this.sSex = sSex == null ? null : sSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_info.s_birthhday
     *
     * @return the value of staff_info.s_birthhday
     *
     * @mbg.generated
     */
    public Date getsBirthhday() {
        return sBirthhday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_info.s_birthhday
     *
     * @param sBirthhday the value for staff_info.s_birthhday
     *
     * @mbg.generated
     */
    public void setsBirthhday(Date sBirthhday) {
        this.sBirthhday = sBirthhday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_info.s_phone
     *
     * @return the value of staff_info.s_phone
     *
     * @mbg.generated
     */
    public String getsPhone() {
        return sPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_info.s_phone
     *
     * @param sPhone the value for staff_info.s_phone
     *
     * @mbg.generated
     */
    public void setsPhone(String sPhone) {
        this.sPhone = sPhone == null ? null : sPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_info.s_password
     *
     * @return the value of staff_info.s_password
     *
     * @mbg.generated
     */
    public String getsPassword() {
        return sPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_info.s_password
     *
     * @param sPassword the value for staff_info.s_password
     *
     * @mbg.generated
     */
    public void setsPassword(String sPassword) {
        this.sPassword = sPassword == null ? null : sPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_info.s_firm_name
     *
     * @return the value of staff_info.s_firm_name
     *
     * @mbg.generated
     */
    public String getsFirmName() {
        return sFirmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_info.s_firm_name
     *
     * @param sFirmName the value for staff_info.s_firm_name
     *
     * @mbg.generated
     */
    public void setsFirmName(String sFirmName) {
        this.sFirmName = sFirmName == null ? null : sFirmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_info.s_remarks
     *
     * @return the value of staff_info.s_remarks
     *
     * @mbg.generated
     */
    public String getsRemarks() {
        return sRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_info.s_remarks
     *
     * @param sRemarks the value for staff_info.s_remarks
     *
     * @mbg.generated
     */
    public void setsRemarks(String sRemarks) {
        this.sRemarks = sRemarks == null ? null : sRemarks.trim();
    }
}