package com.ls.FreightTransport.entity;

public class VehicleType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_type.t_id
     *
     * @mbg.generated
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_type.v_name
     *
     * @mbg.generated
     */
    private String vName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_type.v_load
     *
     * @mbg.generated
     */
    private String vLoad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_type.v_zgk
     *
     * @mbg.generated
     */
    private String vZgk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_type.v_s
     *
     * @mbg.generated
     */
    private String vS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_type.t_id
     *
     * @return the value of vehicle_type.t_id
     *
     * @mbg.generated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_type.t_id
     *
     * @param tId the value for vehicle_type.t_id
     *
     * @mbg.generated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_type.v_name
     *
     * @return the value of vehicle_type.v_name
     *
     * @mbg.generated
     */
    public String getvName() {
        return vName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_type.v_name
     *
     * @param vName the value for vehicle_type.v_name
     *
     * @mbg.generated
     */
    public void setvName(String vName) {
        this.vName = vName == null ? null : vName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_type.v_load
     *
     * @return the value of vehicle_type.v_load
     *
     * @mbg.generated
     */
    public String getvLoad() {
        return vLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_type.v_load
     *
     * @param vLoad the value for vehicle_type.v_load
     *
     * @mbg.generated
     */
    public void setvLoad(String vLoad) {
        this.vLoad = vLoad == null ? null : vLoad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_type.v_zgk
     *
     * @return the value of vehicle_type.v_zgk
     *
     * @mbg.generated
     */
    public String getvZgk() {
        return vZgk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_type.v_zgk
     *
     * @param vZgk the value for vehicle_type.v_zgk
     *
     * @mbg.generated
     */
    public void setvZgk(String vZgk) {
        this.vZgk = vZgk == null ? null : vZgk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_type.v_s
     *
     * @return the value of vehicle_type.v_s
     *
     * @mbg.generated
     */
    public String getvS() {
        return vS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_type.v_s
     *
     * @param vS the value for vehicle_type.v_s
     *
     * @mbg.generated
     */
    public void setvS(String vS) {
        this.vS = vS == null ? null : vS.trim();
    }
}