package com.ls.FreightTransport.entity;

public class VehicleInfo {
    private VehicleType vehicleType;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.v_id
     *
     * @mbg.generated
     */
    private Integer vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.v_license
     *
     * @mbg.generated
     */
    private String vLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.v_type
     *
     * @mbg.generated
     */
    private String vType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.v_color
     *
     * @mbg.generated
     */
    private String vColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.t_type
     *
     * @mbg.generated
     */
    private Integer tType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.v_remarks
     *
     * @mbg.generated
     */
    private String vRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.v_id
     *
     * @return the value of vehicle_info.v_id
     *
     * @mbg.generated
     */
    public Integer getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.v_id
     *
     * @param vId the value for vehicle_info.v_id
     *
     * @mbg.generated
     */
    public void setvId(Integer vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.v_license
     *
     * @return the value of vehicle_info.v_license
     *
     * @mbg.generated
     */
    public String getvLicense() {
        return vLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.v_license
     *
     * @param vLicense the value for vehicle_info.v_license
     *
     * @mbg.generated
     */
    public void setvLicense(String vLicense) {
        this.vLicense = vLicense == null ? null : vLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.v_type
     *
     * @return the value of vehicle_info.v_type
     *
     * @mbg.generated
     */
    public String getvType() {
        return vType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.v_type
     *
     * @param vType the value for vehicle_info.v_type
     *
     * @mbg.generated
     */
    public void setvType(String vType) {
        this.vType = vType == null ? null : vType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.v_color
     *
     * @return the value of vehicle_info.v_color
     *
     * @mbg.generated
     */
    public String getvColor() {
        return vColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.v_color
     *
     * @param vColor the value for vehicle_info.v_color
     *
     * @mbg.generated
     */
    public void setvColor(String vColor) {
        this.vColor = vColor == null ? null : vColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.t_type
     *
     * @return the value of vehicle_info.t_type
     *
     * @mbg.generated
     */
    public Integer gettType() {
        return tType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.t_type
     *
     * @param tType the value for vehicle_info.t_type
     *
     * @mbg.generated
     */
    public void settType(Integer tType) {
        this.tType = tType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.d_id
     *
     * @return the value of vehicle_info.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.d_id
     *
     * @param dId the value for vehicle_info.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.v_remarks
     *
     * @return the value of vehicle_info.v_remarks
     *
     * @mbg.generated
     */
    public String getvRemarks() {
        return vRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.v_remarks
     *
     * @param vRemarks the value for vehicle_info.v_remarks
     *
     * @mbg.generated
     */
    public void setvRemarks(String vRemarks) {
        this.vRemarks = vRemarks == null ? null : vRemarks.trim();
    }
}